// client/src/views/profit/ProfitAnalysis.vue
<template>
  <div class="page-container">
    <div class="page-header">
      <h2>利润分析</h2>
      <div class="header-actions">
        <el-button type="primary" @click="calculateAnalysis">生成分析</el-button>
      </div>
    </div>

    <!-- 分析条件 -->
    <el-form :model="searchForm" inline>
      <el-form-item label="分析类型">
        <el-select v-model="searchForm.type">
          <el-option label="日度分析" value="daily" />
          <el-option label="周度分析" value="weekly" />
          <el-option label="月度分析" value="monthly" />
        </el-select>
      </el-form-item>
      <el-form-item label="日期范围">
        <el-date-picker
          v-model="searchForm.dateRange"
          type="daterange"
          range-separator="至"
          start-placeholder="开始日期"
          end-placeholder="结束日期"
          value-format="YYYY-MM-DD"
        />
      </el-form-item>
      <el-form-item>
        <el-button type="primary" @click="handleSearch">查询</el-button>
        <el-button @click="handleReset">重置</el-button>
      </el-form-item>
    </el-form>

    <!-- 利润总览 -->
    <el-row :gutter="20" class="dashboard-cards">
      <el-col :span="6">
        <el-card shadow="hover">
          <template #header>
            <div class="card-header">
              <span>总销售额</span>
              <el-tag>元</el-tag>
            </div>
          </template>
          <div class="card-value">{{ formatCurrency(overview.totalSales) }}</div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="hover">
          <template #header>
            <div class="card-header">
              <span>总成本</span>
              <el-tag>元</el-tag>
            </div>
          </template>
          <div class="card-value">{{ formatCurrency(overview.totalCost) }}</div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="hover">
          <template #header>
            <div class="card-header">
              <span>毛利润</span>
              <el-tag>元</el-tag>
            </div>
          </template>
          <div class="card-value">{{ formatCurrency(overview.grossProfit) }}</div>
        </el-card>
      </el-col>
      <el-col :span="6">
        <el-card shadow="hover">
          <template #header>
            <div class="card-header">
              <span>净利润</span>
              <el-tag>元</el-tag>
            </div>
          </template>
          <div class="card-value">{{ formatCurrency(overview.netProfit) }}</div>
        </el-card>
      </el-col>
    </el-row>

    <!-- 利润趋势和品类分布 -->
    <el-row :gutter="20" class="analysis-charts">
      <el-col :span="16">
        <el-card shadow="hover">
          <template #header>
            <div class="card-header">
              <span>利润趋势</span>
            </div>
          </template>
          <div ref="trendChart" style="height: 300px"></div>
        </el-card>
      </el-col>
      <el-col :span="8">
        <el-card shadow="hover">
          <template #header>
            <div class="card-header">
              <span>品类利润分布</span>
            </div>
          </template>
          <div ref="categoryChart" style="height: 300px"></div>
        </el-card>
      </el-col>
    </el-row>

    <!-- 商品利润排名 -->
    <el-row :gutter="20" class="analysis-tables">
      <el-col :span="12">
        <el-card shadow="hover">
          <template #header>
            <div class="card-header">
              <span>利润最高商品</span>
            </div>
          </template>
          <el-table :data="topProducts" border stripe>
            <el-table-column prop="productSku" label="SKU" width="120" />
            <el-table-column prop="productName" label="商品名称" />
            <el-table-column prop="salesQuantity" label="销量" width="100" />
            <el-table-column prop="grossProfit" label="毛利润">
              <template #default="{ row }">
                {{ formatCurrency(row.grossProfit) }}
              </template>
            </el-table-column>
            <el-table-column prop="grossProfitRate" label="毛利率">
              <template #default="{ row }">
                {{ (row.grossProfitRate * 100).toFixed(2) }}%
              </template>
            </el-table-column>
          </el-table>
        </el-card>
      </el-col>
      <el-col :span="12">
        <el-card shadow="hover">
          <template #header>
            <div class="card-header">
              <span>利润最低商品</span>
            </div>
          </template>
          <el-table :data="bottomProducts" border stripe>
            <el-table-column prop="productSku" label="SKU" width="120" />
            <el-table-column prop="productName" label="商品名称" />
            <el-table-column prop="salesQuantity" label="销量" width="100" />
            <el-table-column prop="grossProfit" label="毛利润">
              <template #default="{ row }">
                {{ formatCurrency(row.grossProfit) }}
              </template>
            </el-table-column>
            <el-table-column prop="grossProfitRate" label="毛利率">
              <template #default="{ row }">
                {{ (row.grossProfitRate * 100).toFixed(2) }}%
              </template>
            </el-table-column>
          </el-table>
        </el-card>
      </el-col>
    </el-row>

    <!-- 品类分析表格 -->
    <el-card shadow="hover" class="mt-4">
      <template #header>
        <div class="card-header">
          <span>品类分析</span>
        </div>
      </template>
      <el-table :data="categoryAnalysis" border stripe>
        <el-table-column prop="category" label="品类" />
        <el-table-column prop="totalProducts" label="商品数" />
        <el-table-column prop="totalOrders" label="订单数" />
        <el-table-column prop="salesAmount" label="销售额">
          <template #default="{ row }">
            {{ formatCurrency(row.salesAmount) }}
          </template>
        </el-table-column>
        <el-table-column prop="grossProfit" label="毛利润">
          <template #default="{ row }">
            {{ formatCurrency(row.grossProfit) }}
          </template>
        </el-table-column>
        <el-table-column prop="netProfit" label="净利润">
          <template #default="{ row }">
            {{ formatCurrency(row.netProfit) }}
          </template>
        </el-table-column>
        <el-table-column prop="grossProfitRate" label="毛利率">
          <template #default="{ row }">
            {{ (row.grossProfitRate * 100).toFixed(2) }}%
          </template>
        </el-table-column>
        <el-table-column prop="netProfitRate" label="净利率">
          <template #default="{ row }">
            {{ (row.netProfitRate * 100).toFixed(2) }}%
          </template>
        </el-table-column>
      </el-table>
    </el-card>

    <!-- 生成分析对话框 -->
    <el-dialog
      v-model="dialogVisible"
      title="生成利润分析"
      width="500px"
    >
      <el-form :model="analysisForm" label-width="100px">
        <el-form-item label="分析类型">
          <el-select v-model="analysisForm.type">
            <el-option label="日度分析" value="daily" />
            <el-option label="周度分析" value="weekly" />
            <el-option label="月度分析" value="monthly" />
          </el-select>
        </el-form-item>
        <el-form-item label="分析日期">
          <el-date-picker
            v-model="analysisForm.date"
            type="date"
            placeholder="选择日期"
            value-format="YYYY-MM-DD"
          />
        </el-form-item>
      </el-form>
      <template #footer>
        <el-button @click="dialogVisible = false">取消</el-button>
        <el-button type="primary" @click="handleGenerateAnalysis">确定</el-button>
      </template>
    </el-dialog>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, nextTick } from 'vue'
import { ElMessage } from 'element-plus'
import * as echarts from 'echarts'
import type { EChartsOption } from 'echarts'
import profitApi from '@/api/profit'
import { formatCurrency } from '@/utils/format'

// 搜索表单
const searchForm = ref({
  type: 'daily',
  dateRange: [] as string[]
})

// 总览数据
const overview = ref({
  totalSales: 0,
  totalCost: 0,
  grossProfit: 0,
  netProfit: 0,
  grossProfitRate: 0,
  netProfitRate: 0
})

// 商品利润排名
const topProducts = ref([])
const bottomProducts = ref([])

// 品类分析数据
const categoryAnalysis = ref([])

// 图表实例
let trendChart: echarts.ECharts | null = null
let categoryChart: echarts.ECharts | null = null

// 对话框控制
const dialogVisible = ref(false)
const analysisForm = ref({
  type: 'daily',
  date: ''
})

// 初始化图表
const initCharts = () => {
  const trendChartDom = document.querySelector('.trend-chart') as HTMLElement
  const categoryChartDom = document.querySelector('.category-chart') as HTMLElement
  
  trendChart = echarts.init(trendChartDom)
  categoryChart = echarts.init(categoryChartDom)
  
  // 监听窗口大小变化
  window.addEventListener('resize', () => {
    trendChart?.resize()
    categoryChart?.resize()
  })
}

// 更新趋势图表
const updateTrendChart = (data: any) => {
  const option: EChartsOption = {
    tooltip: {
      trigger: 'axis',
      axisPointer: {
        type: 'cross',
        label: {
          backgroundColor: '#6a7985'
        }
      }
    },
    legend: {
      data: ['销售额', '毛利润', '净利润']
    },
    grid: {
      left: '3%',
      right: '4%',
      bottom: '3%',
      containLabel: true
    },
    xAxis: {
      type: 'category',
      boundaryGap: false,
      data: data.dates
    },
    yAxis: {
      type: 'value'
    },
    series: [
      {
        name: '销售额',
        type: 'line',
        data: data.sales
      },
      {
        name: '毛利润',
        type: 'line',
        data: data.grossProfit
      },
      {
        name: '净利润',
        type: 'line',
        data: data.netProfit
      }
    ]
  }
  
  trendChart?.setOption(option)
}

// 更新品类分布图表
const updateCategoryChart = (data: any) => {
  const option: EChartsOption = {
    tooltip: {
      trigger: 'item',
      formatter: '{b}: {c} ({d}%)'
    },
    legend: {
      orient: 'vertical',
      left: 'left',
      type: 'scroll'
    },
    series: [
      {
        type: 'pie',
        radius: ['50%', '70%'],
        avoidLabelOverlap: false,
        label: {
          show: false
        },
        emphasis: {
          label: {
            show: true,
            fontSize: '16',
            fontWeight: 'bold'
          }
        },
        data: data.map((item: any) => ({
          name: item.category,
          value: item.grossProfit
        }))
      }
    ]
  }
  
  categoryChart?.setOption(option)
}

// 查询数据
const handleSearch = async () => {
  try {
    const [startDate, endDate] = searchForm.value.dateRange
    const params = {
      type: searchForm.value.type,
      startDate,
      endDate
    }
    
    const [analysisData, categoryData, productData] = await Promise.all([
      profitApi.getAnalysis(params),
      profitApi.getCategoryAnalysis(params),
      profitApi.getProductAnalysis(params)
    ])
    
    overview.value = analysisData
    categoryAnalysis.value = categoryData
    topProducts.value = productData.topProducts
    bottomProducts.value = productData.bottomProducts
    
    // 更新图表
    nextTick(() => {
      updateTrendChart(analysisData.trend)
      updateCategoryChart(categoryData)
    })
  } catch (error) {
    ElMessage.error('获取分析数据失败')
  }
}

// 重置查询
const handleReset = () => {
  searchForm.value = {
    type: 'daily',
    dateRange: []
  }
  handleSearch()
}

// 显示生成分析对话框
const calculateAnalysis = () => {
  dialogVisible.value = true
  analysisForm.value = {
    type: 'daily',
    date: new Date().toISOString().split('T')[0]
  }
}

// 生成分析数据
const handleGenerateAnalysis = async () => {
  try {
    await profitApi.calculateAnalysis(
      analysisForm.value.date,
      analysisForm.value.type
    )
    ElMessage.success('分析数据生成成功')
    dialogVisible.value = false
    handleSearch()
  } catch (error) {
    ElMessage.error('生成分析数据失败')
  }
}

// 组件挂载时初始化
onMounted(() => {
  initCharts()
  handleSearch()
})
</script>

<style scoped>
.dashboard-cards {
  margin-bottom: 20px;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.card-value {
  font-size: 24px;
  font-weight: bold;
  text-align: center;
  color: #409EFF;
}

.analysis-charts {
  margin-bottom: 20px;
}

.analysis-tables {
  margin-bottom: 20px;
}

.mt-4 {
  margin-top: 16px;
}
</style>

// client/src/pages/profit/ProfitAnalysis.tsx
import React, { useState, useEffect } from 'react';
import { Card, Row, Col, Statistic, DatePicker, Select, Button, message, Space, Table } from 'antd';
import { ArrowUpOutlined, ArrowDownOutlined } from '@ant-design/icons';
import { Line } from '@ant-design/plots';
import profitService, { ProfitSummary } from '../../services/profitService';
import { formatCurrency, formatPercent } from '../../utils/format';

const { RangePicker } = DatePicker;

const ProfitAnalysis: React.FC = () => {
  const [loading, setLoading] = useState(false);
  const [summary, setSummary] = useState<ProfitSummary | null>(null);
  const [dateRange, setDateRange] = useState<[string, string] | null>(null);

  // 加载利润汇总数据
  const loadSummary = async () => {
    try {
      setLoading(true);
      const params = dateRange ? {
        startDate: dateRange[0],
        endDate: dateRange[1]
      } : {};
      const data = await profitService.getProfitSummary(params);
      setSummary(data);
    } catch (error) {
      message.error('加载利润汇总数据失败');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadSummary();
  }, [dateRange]);

  // 计算利润分析
  const handleCalculate = async () => {
    try {
      setLoading(true);
      const today = new Date().toISOString().split('T')[0];
      await profitService.calculateAnalysis(today, 'daily');
      message.success('利润分析计算完成');
      loadSummary();
    } catch (error) {
      message.error('利润分析计算失败');
    } finally {
      setLoading(false);
    }
  };

  // 利润趋势图配置
  const trendConfig = {
    data: summary?.profitTrend || [],
    xField: 'date',
    yField: 'value',
    seriesField: 'type',
    yAxis: {
      label: {
        formatter: (v: string) => formatCurrency(Number(v))
      }
    },
    legend: {
      position: 'top'
    }
  };

  // 处理趋势图数据
  const trendData = summary?.profitTrend.reduce((acc: any[], item) => {
    return acc.concat([
      { date: item.date, type: '销售额', value: item.totalSales },
      { date: item.date, type: '毛利润', value: item.grossProfit },
      { date: item.date, type: '净利润', value: item.netProfit }
    ]);
  }, []) || [];

  return (
    <div className="profit-analysis">
      <div className="page-header" style={{ marginBottom: 24 }}>
        <Row justify="space-between" align="middle">
          <Col>
            <h2>利润分析</h2>
          </Col>
          <Col>
            <Space>
              <RangePicker
                onChange={(dates) => {
                  if (dates) {
                    setDateRange([
                      dates[0]!.format('YYYY-MM-DD'),
                      dates[1]!.format('YYYY-MM-DD')
                    ]);
                  } else {
                    setDateRange(null);
                  }
                }}
              />
              <Button type="primary" onClick={handleCalculate} loading={loading}>
                计算利润
              </Button>
            </Space>
          </Col>
        </Row>
      </div>

      <Row gutter={[24, 24]}>
        {/* 利润概览 */}
        <Col span={6}>
          <Card loading={loading}>
            <Statistic
              title="总销售额"
              value={summary?.totalSales}
              prefix="¥"
              precision={2}
            />
          </Card>
        </Col>
        <Col span={6}>
          <Card loading={loading}>
            <Statistic
              title="毛利润"
              value={summary?.overallGrossProfit}
              prefix="¥"
              precision={2}
              valueStyle={{ color: '#3f8600' }}
            />
            <div style={{ fontSize: 14, color: '#666' }}>
              毛利率：{formatPercent(summary?.overallGrossProfitRate)}
            </div>
          </Card>
        </Col>
        <Col span={6}>
          <Card loading={loading}>
            <Statistic
              title="净利润"
              value={summary?.overallNetProfit}
              prefix="¥"
              precision={2}
              valueStyle={{ color: summary?.overallNetProfit >= 0 ? '#3f8600' : '#cf1322' }}
            />
            <div style={{ fontSize: 14, color: '#666' }}>
              净利率：{formatPercent(summary?.overallNetProfitRate)}
            </div>
          </Card>
        </Col>
        <Col span={6}>
          <Card loading={loading}>
            <Statistic
              title="总成本"
              value={summary?.totalCost}
              prefix="¥"
              precision={2}
              valueStyle={{ color: '#cf1322' }}
            />
          </Card>
        </Col>

        {/* 利润趋势图 */}
        <Col span={24}>
          <Card title="利润趋势" loading={loading}>
            <Line {...trendConfig} data={trendData} height={300} />
          </Card>
        </Col>

        {/* 商品利润排名 */}
        <Col span={12}>
          <Card title="利润最高商品" loading={loading}>
            <ul className="profit-rank-list">
              {summary?.topProfitProducts.map((item, index) => (
                <li key={item.id}>
                  <span className="rank-number">#{index + 1}</span>
                  <span className="product-info">
                    <div className="product-name">{item.name}</div>
                    <div className="product-sku">{item.sku}</div>
                  </span>
                  <span className="profit-info">
                    <div className="profit-amount">
                      {formatCurrency(item.netProfit)}
                    </div>
                    <div className="profit-rate">
                      {formatPercent(item.profitRate)}
                    </div>
                  </span>
                </li>
              ))}
            </ul>
          </Card>
        </Col>
        <Col span={12}>
          <Card title="利润最低商品" loading={loading}>
            <ul className="profit-rank-list">
              {summary?.bottomProfitProducts.map((item, index) => (
                <li key={item.id}>
                  <span className="rank-number">#{index + 1}</span>
                  <span className="product-info">
                    <div className="product-name">{item.name}</div>
                    <div className="product-sku">{item.sku}</div>
                  </span>
                  <span className="profit-info">
                    <div className="profit-amount">
                      {formatCurrency(item.netProfit)}
                    </div>
                    <div className="profit-rate">
                      {formatPercent(item.profitRate)}
                    </div>
                  </span>
                </li>
              ))}
            </ul>
          </Card>
        </Col>

        {/* 品类分析 */}
        <Col span={24}>
          <Card title="品类分析" loading={loading}>
            <Table
              dataSource={summary?.categoryAnalysis}
              columns={[
                {
                  title: '品类',
                  dataIndex: 'category',
                  key: 'category',
                },
                {
                  title: '销售额',
                  dataIndex: 'salesAmount',
                  key: 'salesAmount',
                  render: (value) => formatCurrency(value),
                  sorter: (a, b) => a.salesAmount - b.salesAmount,
                },
                {
                  title: '净利润',
                  dataIndex: 'netProfit',
                  key: 'netProfit',
                  render: (value) => formatCurrency(value),
                  sorter: (a, b) => a.netProfit - b.netProfit,
                },
                {
                  title: '利润率',
                  dataIndex: 'profitRate',
                  key: 'profitRate',
                  render: (value) => formatPercent(value),
                  sorter: (a, b) => a.profitRate - b.profitRate,
                },
                {
                  title: '平均订单金额',
                  dataIndex: 'avgOrderValue',
                  key: 'avgOrderValue',
                  render: (value) => formatCurrency(value),
                  sorter: (a, b) => a.avgOrderValue - b.avgOrderValue,
                },
                {
                  title: '平均订单利润',
                  dataIndex: 'avgProfitPerOrder',
                  key: 'avgProfitPerOrder',
                  render: (value) => formatCurrency(value),
                  sorter: (a, b) => a.avgProfitPerOrder - b.avgProfitPerOrder,
                },
              ]}
              pagination={false}
            />
          </Card>
        </Col>
      </Row>

      <style>
        {`
          .profit-rank-list {
            list-style: none;
            padding: 0;
            margin: 0;
          }
          .profit-rank-list li {
            display: flex;
            align-items: center;
            padding: 12px 0;
            border-bottom: 1px solid #f0f0f0;
          }
          .profit-rank-list li:last-child {
            border-bottom: none;
          }
          .rank-number {
            width: 48px;
            text-align: center;
            font-size: 16px;
            color: #999;
          }
          .product-info {
            flex: 1;
          }
          .product-name {
            font-size: 14px;
            color: #333;
          }
          .product-sku {
            font-size: 12px;
            color: #999;
          }
          .profit-info {
            text-align: right;
            margin-left: 24px;
          }
          .profit-amount {
            font-size: 16px;
            color: #333;
          }
          .profit-rate {
            font-size: 12px;
            color: #999;
          }
        `}
      </style>
    </div>
  );
};

export default ProfitAnalysis;
